### ISSUE TITLE
ToDo: Calculate StrengthMod based on strength.

### ISSUE THREAD

**Issue by bleehu** [Masterdiekillsu/CX-Character-Creator#1]
So that when you change the number in the strength input, the value of the strength mod input changes to match. All of this work will be in the javascript file. The steps that we'll follow are:

1. Create a function called the onchange handler
2. In the onchange handler, store the input tags in vars
3. In the onload function, attach the onchange handler to the strength input tag
4. Do the math!
5. test it!

# 1. Creating your function
You can create your own functions in javascript! More on that here:
https://www.w3schools.com/js/js_functions.asp
You'll have to make your own function in order to control what happens on each onchange or onclick event. Make sure to name it something descriptive. Because of the way we are using your function, it is called an "onchange handler" because it handles what happens when you change what you've entered in the strength input. but the name of the function in the code SHOULD NOT LITTERALLY be "myOnchangeHandler" because that is going to be confusing when you add future onchange handlers for other inputs. Make sure to match all of your curly braces and parenthesis!

https://www.w3schools.com/jsref/event_onchange.asp

# 2. Store input tags as vars
One of the most helpful functions we have in javascript is the document.getElementById("htmlTagId");
There's a good tutorial for that here: (you will have to add id properties in your HTML file if you haven't done that already)
https://www.w3schools.com/jsref/met_document_getelementbyid.asp
In javascript, you can store almost anything in a variable called a var. There technically is an int, string, etc, but Javascript is a loosely typed language, unlike Java which is a strongly typed language. Which means in javascript, you can use a var to hold an int or a string, or a custom data type. No problem. Which makes writing a little easier, but makes debugging a lot harder. When you're done, you should have at least 2 lines of code that look like:
var someVariableName = document.getElementById("the id from the .html file");
You'll need to store both the strength input (to get the strength number FROM) and the strength mod input (to put the strength mod into).

# 3. attach the onchange function
Get ready for a headtrip. Not only can you store ints and strings in vars, but you can actually store _functions_ in a variable in javascript. It can lead to all sorts of weirdness if it is used wrong. But that's exactly what we're about to do. In order for the onchange handler to work, we need to assign the handler to the input that we want to trigger the handler when the input changes. 
The tutorial does this by putting the function in the tag in the .html file, but that looks ugly. And it's more safe to load the handlers in the javascript file when the page loads. 
So in the onload funciton, store the strength input in a variable exactly like you did in step 2. Then do something like this:
variablename.onchange = myFunctionsBetterName;
note, do not use the parenthesis at the end of the function, otherwise you will store what the function _returns_ rather than _the function itself_.

# 4. Do the Math!
Math in javascript is very similar to math in java. Remember that strength mod = (strength - 5) x 4. When you have your number, set the value of the strength mod input to that number. Something like...
myvariablename.value = myNumber.

#5 Test
If you right-click and hit "inspect element" and then click on the console at the bottom of the screen, you should be able to see any errors that your javascript generates.
Feel free to ask me for help whenever you need to!

**Comment by Masterdiekillsu** [comment]
Changes and Commit has been done, stats and the stat mod function all together
